import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <header className="w-full bg-black text-white py-4 px-6 flex justify-between items-center border-b border-gray-800">
  <h1 className="text-xl font-bold">Creators Studio</h1>

  <nav className="flex gap-6 text-gray-300">
    <a href="/" className="hover:text-white">Home</a>
    <a href="#services" className="hover:text-white">Services</a>
    <a href="#pricing" className="hover:text-white">Pricing</a>
    <a href="#contact" className="hover:text-white">Contact</a>
  </nav>
</header>
        {children}
      </body>
    </html>
  );
}
